
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AQUIACABOU DEVOLVA ENQUANTO FACA FIM HORADOSHOW IGUAL RECEBA VARNAME VIRGULAexpr : RECEBA varlist DEVOLVA varlist HORADOSHOW cmds AQUIACABOUvarlist : VARNAMEvarlist : VARNAME VIRGULA varlistcmds : cmdcmds : cmd cmdscmd : ENQUANTO VARNAME FACA cmds FIMcmd : VARNAME IGUAL VARNAME'
    
_lr_action_items = {'RECEBA':([0,],[2,]),'$end':([1,14,],[0,-1,]),'VARNAME':([2,5,6,9,11,12,17,18,19,21,],[4,4,4,13,13,16,19,13,-7,-6,]),'DEVOLVA':([3,4,8,],[5,-2,-3,]),'HORADOSHOW':([4,7,8,],[-2,9,-3,]),'VIRGULA':([4,],[6,]),'ENQUANTO':([9,11,18,19,21,],[12,12,12,-7,-6,]),'AQUIACABOU':([10,11,15,19,21,],[14,-4,-5,-7,-6,]),'FIM':([11,15,19,20,21,],[-4,-5,-7,21,-6,]),'IGUAL':([13,],[17,]),'FACA':([16,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,],[1,]),'varlist':([2,5,6,],[3,7,8,]),'cmds':([9,11,18,],[10,15,20,]),'cmd':([9,11,18,],[11,11,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> RECEBA varlist DEVOLVA varlist HORADOSHOW cmds AQUIACABOU','expr',7,'p_programa','hds_rascunho.py',29),
  ('varlist -> VARNAME','varlist',1,'p_variavel_unica','hds_rascunho.py',33),
  ('varlist -> VARNAME VIRGULA varlist','varlist',3,'p_varias_variaveis','hds_rascunho.py',37),
  ('cmds -> cmd','cmds',1,'p_comando_unico','hds_rascunho.py',41),
  ('cmds -> cmd cmds','cmds',2,'p_varios_comandos','hds_rascunho.py',45),
  ('cmd -> ENQUANTO VARNAME FACA cmds FIM','cmd',5,'p_cmd_while_loop','hds_rascunho.py',49),
  ('cmd -> VARNAME IGUAL VARNAME','cmd',3,'p_cmd_atribuicao','hds_rascunho.py',53),
]
